### ISSUE TITLE
Provide `getSessionUrl` API method, prolong ping interval, extend browser's init options.

### ISSUE THREAD

**Issue by georgiy-abbasov** [AlexanderMoskovkin/saucelabs-connector#16]
These requirments were requested by @AndreyBelym for development browser provider plugin.

UPD. Add ability to disable browser start message.

**Comment by AndreyBelym** [comment]
Please, also allow to specify `--direct-domains` and `--no-ssl-bump-domains` flags of `sauce-tunnel`.
